;TASK 5
;Write a program to display the extended ASCII characters (ASCII codes 80h to FFh).
.MODEL SMALL
.STACK 100H
.DATA

.CODE
    MAIN PROC
    MOV AX,@DATA
    MOV DS,AX 
    
    MOV DX,80H ; AS 80H IS 16 BIT FOR SHOWING OUTPUT WE CHOOSE DX INSTEAD OF DL
    MOV AH,2  ; FOR SHOWING OUTPUT
    REPEAT:
    INT 21h   ; WILL PRINT OUTPUT 
    INC DX    ; DX+=1
    CMP DX,0FFH   ; COMPARE DX VALUE WITH FF
    JL REPEAT     ; IF DX IS LESS THAN FF IT WILL BACK TO LINE 14
    
    MAIN ENDP
END MAIN